# Use the official Golang image
FROM golang:1.21-alpine

# Install git, required for fetching Go dependencies
RUN apk add --no-cache git

# Set the working directory
WORKDIR /app

# Install Air for hot reloading
RUN go install github.com/cosmtrek/air@v1.28.0

# Copy the go.mod and go.sum file to handle dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the entire project
COPY . .

# Set environment variables necessary for the Go application
ENV APP_ENV=local

# Expose the necessary ports (make sure these match your actual application)
EXPOSE 9014 5114

# Command to run the application using Air for hot reloading
CMD ["air", "-c", ".air.toml"]
